#ifndef CONFIG_RSK_H
#define CONFIG_RSK_H

#include "../../config.h"

#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX 20

#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED 6

#undef MOUSEKEY_MOVE_DELTA
#define MOUSEKEY_MOVE_DELTA 1

#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 12

#undef MOUSEKEY_DELAY
#define MOUSEKEY_DELAY 0

#undef DEBOUNCE
#define DEBOUNCE 5

#endif
